language: c

matrix:
    include:
        - os: windows
          compiler: clang
          env: BUILDDIR="..\build\Debug" 
        - os: windows
          compiler: gcc
          env: BUILDDIR="..\build\Debug"
        - os: linux
          compiler: clang
          env: BUILDDIR="../build" 
        - os: linux
          compiler: clang
          env: TOOL="-DMZ_ZLIB=OFF" BUILDDIR="../build"
        - os: linux
          compiler: clang
          env: TOOL="-DMZ_BZIP=OFF" BUILDDIR="../build"
        - os: linux
          compiler: clang
          env: TOOL="-DMZ_LZMA=OFF" BUILDDIR="../build"
        - os: linux
          compiler: clang
          env: TOOL="-DMZ_WZAES=OFF" BUILDDIR="../build"
        - os: linux
          compiler: clang
          env: TOOL="-DMZ_PKCRYPT=OFF" BUILDDIR="../build"
        - os: linux
          compiler: clang
          env: TOOL="-DMZ_COMPRESS_ONLY=ON" BUILDDIR="../build"
        - os: linux
          compiler: clang
          env: TOOL="-DMZ_DECOMPRESS_ONLY=ON" BUILDDIR="../build"
        - os: linux
          compiler: clang
          env: TOOL="-DMZ_PKCRYPT=OFF -DMZ_WZAES=OFF" BUILDDIR="../build"
        - os: linux
          compiler: clang
          env: TOOL="-DMZ_OPENSSL=ON" BUILDDIR="../build"
        - os: linux
          compiler: gcc
          env: BUILDDIR="../build"
        - os: osx
          compiler: clang
          env: BUILDDIR="../build"
        - os: osx
          compiler: gcc
          env: BUILDDIR="../build"
        - os: osx
          compiler: clang
          env: TOOL="-DMZ_LIBCOMP=ON" BUILDDIR="../build"
        - os: osx
          compiler: gcc
          env: TOOL="-DMZ_LIBCOMP=ON" BUILDDIR="../build"
        - os: osx
          compiler: clang
          env: TOOL="-DMZ_OPENSSL=ON -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_INCLUDE_DIRS=/usr/local/opt/openssl/include -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl/lib/libcrypto.dylib -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl/lib/libssl.dylib" BUILDDIR="../build"

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux"   ]]; then sudo apt-get install libbsd-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux"   ]]; then sudo apt-get install libssl-dev; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx"     ]]; then brew install openssl; fi

before_script:
    - mkdir build
    - cd build
    - cmake .. -DMZ_BUILD_TEST=ON -DMZ_BUILD_UNIT_TEST=ON $TOOL 

script:
    - cmake --build .
    - ctest --output-on-failure -C Debug
